---
title: "Twine AGBs - Zusätze"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Zusatz zur Haftungsbeschränkung / Disclaimer on Liability {.tabset #zusatz1}


## Deutsch

Twine kann nicht für unrichtige Angaben in den Anmeldungen und/oder Daten, die von den Kunden bereitgestellt werden, verantwortlich gemacht werden. Folglich übernimmt Twine keine Verantwortung für die Richtigkeit der Ergebnisse der Datenerhebung durch Twine sowie für die Inhalte des auf diesen Ergebnissen basierenden Persönlichkeitsporträts im Kontext von Freundschaften oder Partnerschaften. Twine ist ausschließlich dazu verpflichtet, eine Serviceleistung in Form von IT-Dienstleistungen zur Kontaktaufnahme bereitzustellen; jedoch übernimmt Twine keine Gewähr für den Erfolg im Sinne einer Partnervermittlung oder erfolgreicher Kontakte. Twine stellt lediglich die technische Infrastruktur bereit, die im Allgemeinen eine Kontaktaufnahme anhand des zuvor ausgefüllten Fragebogens ermöglicht. Twine haftet nicht für einen möglichen Missbrauch von Informationen. 
Es besteht die Möglichkeit, dass Kunden den von Twine bereitgestellten Service zur Kontaktaufnahme trotz eines Verbots in unzulässiger oder gesetzwidriger Weise nutzen. Twine übernimmt keine Verantwortung für eine solche unzulässige und/oder gesetzwidrige Nutzung und schließt jegliche Haftung aus. Gleichzeitig übernimmt Twine keine Verantwortung dafür, dass von Kunden selbst Dritten zugänglich gemachte Angaben und Informationen von diesen möglicherweise missbraucht werden könnten. Twine gewährleistet nicht den jederzeitigen ordnungsgemäßen Betrieb bzw. die ununterbrochene Nutzbarkeit bzw. Erreichbarkeit des Services. Insbesondere lehnt Twine jegliche Verantwortung für Beeinträchtigungen der Qualität des Servicezugangs aufgrund von höherer Gewalt oder Ereignissen ab, die nicht in der Verantwortung von Twine liegen. Ebenso übernimmt Twine keine Verantwortung für die unautorisierte Erlangung persönlicher Daten von Kunden durch Dritte, beispielsweise durch nicht autorisierten Zugriff auf die Datenbank.

## English 

Twine cannot be held responsible for inaccurate information in registrations and/or data provided by customers. Consequently, Twine assumes no responsibility for the accuracy of the results of data collection by Twine and for the content of personality portraits based on these results in the context of friendships or partnerships. Twine is solely obligated to provide a service in the form of IT services for contacting; however, Twine does not guarantee success in terms of matchmaking or successful contacts. Twine merely provides the technical infrastructure that generally enables contact based on the previously filled-out questionnaire. Twine is not liable for potential misuse of information. There is a possibility that customers may use the service provided by Twine for contact in an unauthorized or illegal manner despite a prohibition. Twine assumes no responsibility for such unauthorized and/or illegal use and disclaims all liability. At the same time, Twine does not assume responsibility for information and data made accessible by customers to third parties, which may be potentially misused by them. Twine does not guarantee the continuous proper operation or uninterrupted usability or accessibility of the service at all times. In particular, Twine disclaims any responsibility for impairments to the quality of service access due to force majeure or events beyond the control of Twine. Likewise, Twine does not assume responsibility for the unauthorized acquisition of personal data of customers by third parties, such as through unauthorized access to the database.

# Zusatz zur Kündigung sowie Verlängerung des Abonnementvertrages / Disclaimer on Termination and Extension of the Subscription Agreement {.tabset #zusatz2}

## Deutsch

Dem Kunden steht das Recht zu, den Vertrag über die kostenfreie Standardmitgliedschaft unverzüglich zu kündigen. Die Kündigung der Standardmitgliedschaft wird wirksam durch die Aktivierung des "Profil löschen"-Buttons im Abschnitt "Mein Profil" / "Daten & Einstellungen" / "Profil verwalten" / "Profilstatus" in der App. Die Wirksamkeit der Kündigung wird durch die Bestätigung dieses Vorgangs mittels Eingabe des persönlichen Passworts gewährleistet. Bestehende Zahlungsverpflichtungen bleiben vorbehaltlich der Regelungen zum Widerruf bestehen. Der Vertragspartner ist berechtigt, das Premium-Abonnement ordentlich zum Ende der erstmaligen Vertragslaufzeit zu kündigen. Die ordentliche Kündigung der Premium-Mitgliedschaft entfaltet erst zum Abschluss der vertraglich festgelegten Erstlaufzeit ihre Wirkung und ist in diesem Zusammenhang nicht erstattungsfähig. Bestehende Zahlungsverpflichtungen aus dem Abonnementvertrag bleiben davon unberührt. Die Frist für die ordentliche Kündigung des Premium-Abonnements zum Ende der Erstlaufzeit ist durch die produktbezogenen Vertragsinhalte bestimmt, die während des Bestellvorgangs auf der Bestellseite von Twine vom Kunden bestätigt werden. Zusätzlich wird der Kunde in der Bestellbestätigung per E-Mail über die Kündigungsfrist im Zusammenhang mit dem Abonnement informiert. Die Kündigung entfaltet ihre Wirksamkeit ausschließlich durch eine ausdrückliche Erklärung in Textform, beispielsweise per E-Mail oder über die Kündigungsschaltfläche innerhalb der App. Zur eindeutigen Identifikation sollte die Kündigung des Kunden folgende zwei Informationen enthalten: 

1.	Die bei Twine hinterlegte E-Mail-Adresse oder Profil-ID. 
2.	Das Service-Kennwort. 

Sofern der Kunde seine Abonnement-Mitgliedschaft über Drittanbieter wie Apple oder Google Play erworben hat, gelten folgende Bestimmungen für die Beendigung des Vertragsverhältnisses: Twine ermöglicht es seinen Nutzern, kostenpflichtige Leistungen über die Plattformen von Apple und Google Play in Anspruch zu nehmen (sogenannte "In-App-Käufe"). Die Bildung des Vertragsverhältnisses erfolgt durch die Bestätigung seitens Twine per E-Mail an den Kunden. Die Drittanbieter haben vorgeschriebene Regelwerke für den Vertragsabschluss, die Zahlung und die Beendigung des Vertrags, welche der Kunde durch Akzeptanz der Nutzungsbedingungen anerkennt und auf die Twine keinen Einfluss hat. Entscheidet sich der Kunde für den Abschluss eines Vertrags über einen Drittanbieter, obliegt es ihm, die in den Nutzungsbedingungen des Drittanbieters festgelegten Regelungen für den Vertragsabschluss, die Zahlung und die Vertragsbeendigung zu befolgen. Im Falle von Unstimmigkeiten zwischen den Regelungen des Drittanbieters und den vorliegenden Allgemeinen Geschäftsbedingungen von Twine haben die Regelungen des Drittanbieters Vorrang. Insbesondere wird der Kunde vom Drittanbieter aufgefordert, seinen Kauf zu bestätigen, wobei die zuvor vereinbarte Zahlungsmethode mit dem Drittanbieter maßgeblich ist. Möchte der Kunde eine über In-App-Käufe erworbene Abonnement-Mitgliedschaft ändern oder beenden, ist es erforderlich, dies über sein Konto beim Drittanbieter vorzunehmen. Hierbei muss sich der Kunde einloggen und den Anweisungen des Drittanbieters zur Beendigung, zum Widerruf oder zur Kündigung des Vertrags folgen. Eventuelle Rückerstattungen erfolgen gemäß den Regelungen des Drittanbieters, entweder im Verhältnis des Drittanbieters zum Kunden oder im Verhältnis des Kunden zu Twine. Auch die ordentliche Kündigung der kostenpflichtigen Abonnement-Mitgliedschaft über Drittanbieter bewirkt nicht automatisch die Kündigung der Basis-Mitgliedschaft. Bei einer Bestellung über Twine erfolgt eine automatische Verlängerung des Vertrags für die kostenpflichtige Premium-Mitgliedschaft, sofern der Kunde seinen Vertrag nicht rechtzeitig vor Ablauf der Erstlaufzeit unter Beachtung der ordentlichen Kündigungsfrist beendet. Nach erfolgter Vertragsverlängerung erfolgt die monatliche Zahlung gemäß der vereinbarten Gebühr im Voraus. Der Abonnement-Vertrag kann jederzeit ordentlich mit einer Frist von einem Monat gekündigt werden. Bei der Bestellung einer Abonnementvertrages wird der Kunde sowohl unmittelbar vor der Abgabe seiner Bestellung als auch in der Bestellbestätigung über die Modalitäten und Bedingungen einer möglichen automatischen Verlängerung bei nicht rechtzeitiger Kündigung informiert. Bei Abschluss eines Abonnementvertrages über Drittanbieter wie Apple oder Google Play ergeben sich die Konditionen für eine mögliche automatische Verlängerung aus dem jeweiligen Angebot, den Regelungen im Drittanbieter-Konto sowie aus der Bestellbestätigung, die dem Kunden bei Vertragsschluss übermittelt wird. Eine außerordentliche Kündigung unterliegt den gesetzlichen Vorschriften und muss ebenfalls in Textform erfolgen. Es sei darauf hingewiesen, dass die Kündigung des kostenpflichtigen Abonnementvertrages nicht automatisch zur Kündigung der kostenlosen Mitgliedschaft führt.


## English

The customer has the right to terminate the contract for the free standard membership immediately. The termination of the standard membership becomes effective by activating the "Delete Profile" button in the "My Profile" / "Data & Settings" / "Manage Profile" / "Profile Status" section in the app. The effectiveness of the termination is ensured by confirming this process by entering the personal password. Existing payment obligations remain in force, subject to the regulations regarding revocation. The contractual partner is entitled to terminate the premium subscription at the end of the initial contract term. The ordinary termination of the premium membership only takes effect at the conclusion of the contractually determined initial term and is not refundable in this context. Existing payment obligations from the subscription agreement remain unaffected. The deadline for the ordinary termination of the premium subscription at the end of the initial term is determined by the product-related contract contents confirmed by the customer during the ordering process on Twine's order page. In addition, the customer is informed about the cancellation period in connection with the subscription in the order confirmation by email. The termination takes effect exclusively through an explicit declaration in written form, such as by email or through the termination button within the app. For clear identification, the customer's termination should include the following two pieces of information: 

1.	The email address or profile ID registered with Twine. 
2.	The service password. 

If the customer has acquired the subscription membership through third-party providers such as Apple or Google Play, the following provisions apply for the termination of the contractual relationship: Twine enables its users to utilize paid services through the platforms of Apple and Google Play (so-called "In-App Purchases"). The formation of the contractual relationship occurs through confirmation by Twine via email to the customer. Third-party providers have prescribed regulations for contract conclusion, payment, and termination, which the customer acknowledges by accepting the terms of use, and Twine has no influence over them. If the customer decides to conclude a contract through a third-party provider, it is their responsibility to follow the regulations stipulated in the terms of use of the third-party provider for contract conclusion, payment, and contract termination. In case of discrepancies between the regulations of the third-party provider and the present Terms and Conditions of Twine, the regulations of the third-party provider take precedence. In particular, the customer is prompted by the third-party provider to confirm their purchase, with the previously agreed-upon payment method with the third-party provider being decisive. If the customer wants to modify or terminate a subscription membership purchased via In-App Purchases, it is necessary to do so through their account with the third-party provider. The customer must log in and follow the instructions of the third-party provider for termination, revocation, or termination of the contract. Any refunds will be made according to the regulations of the third-party provider, either in the relationship between the third-party provider and the customer or in the relationship between the customer and Twine. Also, the ordinary termination of the paid subscription membership through third-party providers does not automatically result in the termination of the basic membership. When ordering through Twine, the subscription for the paid premium membership is automatically extended if the customer does not terminate the contract in a timely manner before the expiration of the initial term, observing the ordinary notice period. After the contract extension, monthly payment is made in advance at the agreed-upon price. The subscription agreement can be terminated with a notice period of one month at any time. When ordering a subscription agreement, the customer is informed both immediately before placing their order and in the order confirmation about the modalities and conditions of a possible automatic extension in case of untimely termination. When concluding a subscription agreement through third-party providers such as Apple or Google Play, the conditions for a possible automatic extension arise from the respective offer, the regulations in the third-party provider's account, and the order confirmation sent to the customer upon conclusion of the contract. Extraordinary termination is subject to legal regulations and must also be in written form. It should be noted that the termination of the paid subscription agreement does not automatically lead to the termination of the free membership.


